using Microsoft.Extensions.Logging;
using Moq;
using OpenUpMan.Data;
using OpenUpMan.Domain;
using OpenUpMan.Services;

namespace OpenUpMan.Tests.Services
{
    public class ProjectServiceUnitTests
    {
        private static ILogger<ProjectService> CreateMockLogger()
        {
            return new Mock<ILogger<ProjectService>>().Object;
        }

        private static IUserRepository CreateMockUserRepository()
        {
            return new Mock<IUserRepository>().Object;
        }

        private static IProjectUserRepository CreateMockProjectUserRepository()
        {
            return new Mock<IProjectUserRepository>().Object;
        }

        private static IProjectPhaseRepository CreateMockProjectPhaseRepository()
        {
            return new Mock<IProjectPhaseRepository>().Object;
        }

        private static ProjectService CreateProjectService(IProjectRepository projectRepo)
        {
            return new ProjectService(
                projectRepo,
                CreateMockUserRepository(),
                CreateMockProjectUserRepository(),
                CreateMockProjectPhaseRepository(),
                CreateMockLogger()
            );
        }

        #region CreateProject Tests

        [Fact]
        public async Task CreateProject_ReturnsSuccess_WithAutogeneratedIdentifier()
        {
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            // Mock for identifier generation - first call returns null (identifier is available)
            mockRepo.Setup(r => r.GetByIdentifierAsync(It.IsAny<string>(), default)).ReturnsAsync((Project?)null);
            mockRepo.Setup(r => r.AddAsync(It.IsAny<Project>(), default)).Returns(Task.CompletedTask).Verifiable();
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask).Verifiable();

            var service = CreateProjectService(mockRepo.Object);
            var ownerId = Guid.NewGuid();

            var result = await service.CreateProjectAsync("Proyecto Test", DateTime.UtcNow, ownerId, "Descripción test");

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("exitosa", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.NotNull(result.Project);
            Assert.NotEmpty(result.Project.Identifier);
            Assert.StartsWith("PROY-", result.Project.Identifier);
            Assert.Equal("Proyecto Test", result.Project.Name);
            mockRepo.Verify(r => r.AddAsync(It.IsAny<Project>(), default), Times.Once);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Once);
        }

        [Fact]
        public async Task CreateProject_GeneratesUniqueIdentifier_WhenFirstAttemptExists()
        {
            var ownerId = Guid.NewGuid();
            var year = DateTime.Now.Year.ToString().Substring(2);
            var firstIdentifier = $"PROY-{year}0001";
            var secondIdentifier = $"PROY-{year}0002";
            var existing = new Project(firstIdentifier, "Existing Project", DateTime.UtcNow, ownerId);
            
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            // First check returns existing project, second check returns null (available)
            mockRepo.SetupSequence(r => r.GetByIdentifierAsync(It.IsAny<string>(), default))
                .ReturnsAsync(existing)
                .ReturnsAsync((Project?)null);
            mockRepo.Setup(r => r.AddAsync(It.IsAny<Project>(), default)).Returns(Task.CompletedTask).Verifiable();
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask).Verifiable();

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.CreateProjectAsync("New Project", DateTime.UtcNow, ownerId);

            Assert.True(result.Success);
            Assert.NotNull(result.Project);
            Assert.NotEqual(firstIdentifier, result.Project.Identifier);
            Assert.StartsWith("PROY-", result.Project.Identifier);
            mockRepo.Verify(r => r.AddAsync(It.IsAny<Project>(), default), Times.Once);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Once);
        }

        [Theory]
        [InlineData("")]
        [InlineData("  ")]
        public async Task CreateProject_ReturnsError_WhenNameIsInvalid(string name)
        {
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            var service = CreateProjectService(mockRepo.Object);
            var ownerId = Guid.NewGuid();

            var result = await service.CreateProjectAsync(name, DateTime.UtcNow, ownerId);

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("requerido", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Null(result.Project);
        }

        [Fact]
        public async Task CreateProject_ReturnsError_WhenNameIsNull()
        {
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            var service = CreateProjectService(mockRepo.Object);
            var ownerId = Guid.NewGuid();

#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type
            var result = await service.CreateProjectAsync(null, DateTime.UtcNow, ownerId);
#pragma warning restore CS8625

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("requerido", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Null(result.Project);
        }

        [Fact]
        public async Task CreateProject_SetsCorrectDefaultState()
        {
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdentifierAsync(It.IsAny<string>(), default)).ReturnsAsync((Project?)null);
            mockRepo.Setup(r => r.AddAsync(It.IsAny<Project>(), default)).Returns(Task.CompletedTask);
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask);

            var service = CreateProjectService(mockRepo.Object);
            var ownerId = Guid.NewGuid();

            var result = await service.CreateProjectAsync("Test Project", DateTime.UtcNow, ownerId);

            Assert.True(result.Success);
            Assert.NotNull(result.Project);
            Assert.Equal(ProjectState.CREATED, result.Project.State);
        }

        [Fact]
        public async Task GenerateUniqueIdentifier_ReturnsUniqueIdentifier()
        {
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdentifierAsync(It.IsAny<string>(), default)).ReturnsAsync((Project?)null);

            var service = CreateProjectService(mockRepo.Object);

            var identifier = await service.GenerateUniqueIdentifierAsync();

            Assert.NotEmpty(identifier);
            Assert.StartsWith("PROY-", identifier);
            Assert.Matches(@"PROY-\d{6}", identifier); // Format: PROY-YYXXXX
        }

        #endregion

        #region GetProjectById Tests

        [Fact]
        public async Task GetProjectById_ReturnsSuccess_WhenProjectExists()
        {
            var ownerId = Guid.NewGuid();
            var projectId = Guid.NewGuid();
            var existingProject = new Project("PROY-001", "Test Project", DateTime.UtcNow, ownerId);

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync(existingProject);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.GetProjectByIdAsync(projectId);

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.NotNull(result.Project);
            mockRepo.Verify(r => r.GetByIdAsync(projectId, default), Times.Once);
        }

        [Fact]
        public async Task GetProjectById_ReturnsNotFound_WhenProjectDoesNotExist()
        {
            var projectId = Guid.NewGuid();
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync((Project?)null);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.GetProjectByIdAsync(projectId);

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Null(result.Project);
        }

        #endregion

        #region GetProjectByIdentifier Tests

        [Fact]
        public async Task GetProjectByIdentifier_ReturnsSuccess_WhenProjectExists()
        {
            var ownerId = Guid.NewGuid();
            var existingProject = new Project("PROY-001", "Test Project", DateTime.UtcNow, ownerId);

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdentifierAsync("PROY-001", default)).ReturnsAsync(existingProject);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.GetProjectByIdentifierAsync("PROY-001");

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.NotNull(result.Project);
            Assert.Equal("PROY-001", result.Project.Identifier);
            mockRepo.Verify(r => r.GetByIdentifierAsync("PROY-001", default), Times.Once);
        }

        [Fact]
        public async Task GetProjectByIdentifier_ReturnsNotFound_WhenProjectDoesNotExist()
        {
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdentifierAsync("PROY-999", default)).ReturnsAsync((Project?)null);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.GetProjectByIdentifierAsync("PROY-999");

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Null(result.Project);
            mockRepo.Verify(r => r.GetByIdentifierAsync("PROY-999", default), Times.Once);
        }

        #endregion

        #region GetProjectsByOwner Tests

        [Fact]
        public async Task GetProjectsByOwner_ReturnsProjects_WhenProjectsExist()
        {
            var ownerId = Guid.NewGuid();
            var projects = new List<Project>
            {
                new Project("PROY-001", "Project 1", DateTime.UtcNow, ownerId),
                new Project("PROY-002", "Project 2", DateTime.UtcNow, ownerId)
            };

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByOwnerAsync(ownerId, default)).ReturnsAsync(projects);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.GetProjectsByOwnerAsync(ownerId);

            Assert.NotNull(result);
            Assert.Equal(2, result.Count());
            mockRepo.Verify(r => r.GetByOwnerAsync(ownerId, default), Times.Once);
        }

        [Fact]
        public async Task GetProjectsByOwner_ReturnsEmpty_WhenNoProjectsExist()
        {
            var ownerId = Guid.NewGuid();
            var projects = new List<Project>();

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByOwnerAsync(ownerId, default)).ReturnsAsync(projects);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.GetProjectsByOwnerAsync(ownerId);

            Assert.NotNull(result);
            Assert.Empty(result);
            mockRepo.Verify(r => r.GetByOwnerAsync(ownerId, default), Times.Once);
        }

        #endregion

        #region UpdateProject Tests

        [Fact]
        public async Task UpdateProject_ReturnsSuccess_WhenProjectExists()
        {
            var ownerId = Guid.NewGuid();
            var projectId = Guid.NewGuid();
            var existingProject = new Project("PROY-001", "Old Name", DateTime.UtcNow, ownerId, "Old description");

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync(existingProject);
            mockRepo.Setup(r => r.UpdateAsync(It.IsAny<Project>(), default)).Returns(Task.CompletedTask);
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask).Verifiable();

            var service = CreateProjectService(mockRepo.Object);
            var newStartDate = DateTime.UtcNow.AddDays(10);

            var result = await service.UpdateProjectAsync(projectId, "New Name", "New description", newStartDate);

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("actualizado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.NotNull(result.Project);
            Assert.Equal("New Name", result.Project.Name);
            Assert.Equal("New description", result.Project.Description);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Once);
        }

        [Fact]
        public async Task UpdateProject_ReturnsNotFound_WhenProjectDoesNotExist()
        {
            var projectId = Guid.NewGuid();
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync((Project?)null);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.UpdateProjectAsync(projectId, "New Name", "New description", DateTime.UtcNow);

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Null(result.Project);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Never);
        }

        #endregion

        #region ChangeProjectState Tests

        [Theory]
        [InlineData(ProjectState.ACTIVE)]
        [InlineData(ProjectState.ARCHIVED)]
        [InlineData(ProjectState.CLOSED)]
        public async Task ChangeProjectState_ReturnsSuccess_WhenProjectExists(ProjectState newState)
        {
            var ownerId = Guid.NewGuid();
            var projectId = Guid.NewGuid();
            var existingProject = new Project("PROY-001", "Test Project", DateTime.UtcNow, ownerId);

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync(existingProject);
            mockRepo.Setup(r => r.UpdateAsync(It.IsAny<Project>(), default)).Returns(Task.CompletedTask);
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask).Verifiable();

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.ChangeProjectStateAsync(projectId, newState);

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("actualizado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.NotNull(result.Project);
            Assert.Equal(newState, result.Project.State);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Once);
        }

        [Fact]
        public async Task ChangeProjectState_ReturnsNotFound_WhenProjectDoesNotExist()
        {
            var projectId = Guid.NewGuid();
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync((Project?)null);

            var service = CreateProjectService(mockRepo.Object);

            var result = await service.ChangeProjectStateAsync(projectId, ProjectState.ACTIVE);

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);
            Assert.Null(result.Project);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Never);
        }

        #endregion

        #region DeleteProject Tests

        [Fact]
        public async Task DeleteProject_ReturnsNotFound_WhenProjectDoesNotExist()
        {
            var projectId = Guid.NewGuid();
            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync((Project?)null);

            var mockProjectUserRepo = new Mock<IProjectUserRepository>(MockBehavior.Strict);
            var mockProjectPhaseRepo = new Mock<IProjectPhaseRepository>(MockBehavior.Strict);

            var service = new ProjectService(
                mockRepo.Object,
                CreateMockUserRepository(),
                mockProjectUserRepo.Object,
                mockProjectPhaseRepo.Object,
                CreateMockLogger()
            );

            var result = await service.DeleteProjectAsync(projectId);

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("encontrado", result.Message, StringComparison.OrdinalIgnoreCase);

            mockRepo.Verify(r => r.GetByIdAsync(projectId, default), Times.Once);
            mockProjectUserRepo.Verify(r => r.GetByProjectIdAsync(It.IsAny<Guid>(), default), Times.Never);
            mockProjectPhaseRepo.Verify(r => r.GetByProjectIdAsync(It.IsAny<Guid>(), default), Times.Never);
        }

        [Fact]
        public async Task DeleteProject_DeletesAssociatedUsersAndPhases_WhenProjectExists()
        {
            var ownerId = Guid.NewGuid();
            var existingProject = new Project("PROY-DEL", "To Delete", DateTime.UtcNow, ownerId);
            var projectId = existingProject.Id;
            

            var projectPhases = new List<ProjectPhase>
            {
                new ProjectPhase(projectId, PhaseCode.INCEPTION, "Phase 1", 1),
                new ProjectPhase(projectId, PhaseCode.ELABORATION, "Phase 2", 2)
            };

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync(existingProject);
            mockRepo.Setup(r => r.DeleteAsync(existingProject, default)).Returns(Task.CompletedTask).Verifiable();
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask).Verifiable();

            var mockProjectUserRepo = new Mock<IProjectUserRepository>(MockBehavior.Strict);
            mockProjectUserRepo.Setup(r => r.GetByProjectIdAsync(projectId, default)).ReturnsAsync(new List<ProjectUser>());
            mockProjectUserRepo.Setup(r => r.RemoveAsync(It.IsAny<ProjectUser>(), default)).Returns(Task.CompletedTask).Verifiable();

            var mockProjectPhaseRepo = new Mock<IProjectPhaseRepository>(MockBehavior.Strict);
            mockProjectPhaseRepo.Setup(r => r.GetByProjectIdAsync(projectId, default)).ReturnsAsync(projectPhases);
            mockProjectPhaseRepo.Setup(r => r.DeleteAsync(It.IsAny<ProjectPhase>(), default)).Returns(Task.CompletedTask).Verifiable();

            var service = new ProjectService(
                mockRepo.Object,
                CreateMockUserRepository(),
                mockProjectUserRepo.Object,
                mockProjectPhaseRepo.Object,
                CreateMockLogger()
            );

            var result = await service.DeleteProjectAsync(projectId);

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("eliminado", result.Message, StringComparison.OrdinalIgnoreCase);

            mockRepo.Verify(r => r.GetByIdAsync(projectId, default), Times.Once);
            mockProjectUserRepo.Verify(r => r.GetByProjectIdAsync(projectId, default), Times.Once);
            mockProjectPhaseRepo.Verify(r => r.GetByProjectIdAsync(projectId, default), Times.Once);
            mockProjectPhaseRepo.Verify(r => r.DeleteAsync(It.IsAny<ProjectPhase>(), default), Times.Exactly(projectPhases.Count));
            mockRepo.Verify(r => r.DeleteAsync(existingProject, default), Times.Once);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Once);
        }

        [Fact]
        public async Task DeleteProject_Succeeds_WhenNoAssociatedUsersOrPhases()
        {
            var ownerId = Guid.NewGuid();
            var existingProject = new Project("PROY-DEL-EMPTY", "To Delete Empty", DateTime.UtcNow, ownerId);
            var projectId = existingProject.Id;

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync(existingProject);
            mockRepo.Setup(r => r.DeleteAsync(existingProject, default)).Returns(Task.CompletedTask).Verifiable();
            mockRepo.Setup(r => r.SaveChangesAsync(default)).Returns(Task.CompletedTask).Verifiable();

            var mockProjectUserRepo = new Mock<IProjectUserRepository>(MockBehavior.Strict);
            mockProjectUserRepo.Setup(r => r.GetByProjectIdAsync(projectId, default)).ReturnsAsync(new List<ProjectUser>());

            var mockProjectPhaseRepo = new Mock<IProjectPhaseRepository>(MockBehavior.Strict);
            mockProjectPhaseRepo.Setup(r => r.GetByProjectIdAsync(projectId, default)).ReturnsAsync(new List<ProjectPhase>());

            var service = new ProjectService(
                mockRepo.Object,
                CreateMockUserRepository(),
                mockProjectUserRepo.Object,
                mockProjectPhaseRepo.Object,
                CreateMockLogger()
            );

            var result = await service.DeleteProjectAsync(projectId);

            Assert.True(result.Success);
            Assert.Equal(ServiceResultType.Success, result.ResultType);
            Assert.Contains("eliminado", result.Message, StringComparison.OrdinalIgnoreCase);

            mockProjectUserRepo.Verify(r => r.RemoveAsync(It.IsAny<ProjectUser>(), default), Times.Never);
            mockProjectPhaseRepo.Verify(r => r.DeleteAsync(It.IsAny<ProjectPhase>(), default), Times.Never);
            mockProjectUserRepo.Verify(r => r.GetByProjectIdAsync(projectId, default), Times.Once);
            mockProjectPhaseRepo.Verify(r => r.GetByProjectIdAsync(projectId, default), Times.Once);
            mockRepo.Verify(r => r.DeleteAsync(existingProject, default), Times.Once);
            mockRepo.Verify(r => r.SaveChangesAsync(default), Times.Once);
        }

        [Fact]
        public async Task DeleteProject_ReturnsError_WhenDeletionThrows()
        {
            var ownerId = Guid.NewGuid();
            var existingProject = new Project("PROY-DEL-ERR", "To Delete Err", DateTime.UtcNow, ownerId);
            var projectId = existingProject.Id;

            var mockRepo = new Mock<IProjectRepository>(MockBehavior.Strict);
            mockRepo.Setup(r => r.GetByIdAsync(projectId, default)).ReturnsAsync(existingProject);

            var mockProjectUserRepo = new Mock<IProjectUserRepository>(MockBehavior.Strict);
            mockProjectUserRepo.Setup(r => r.GetByProjectIdAsync(projectId, default)).ThrowsAsync(new Exception("boom"));

            var mockProjectPhaseRepo = new Mock<IProjectPhaseRepository>(MockBehavior.Strict);

            var service = new ProjectService(
                mockRepo.Object,
                CreateMockUserRepository(),
                mockProjectUserRepo.Object,
                mockProjectPhaseRepo.Object,
                CreateMockLogger()
            );

            var result = await service.DeleteProjectAsync(projectId);

            Assert.False(result.Success);
            Assert.Equal(ServiceResultType.Error, result.ResultType);
            Assert.Contains("Error al eliminar", result.Message, StringComparison.OrdinalIgnoreCase);

            mockRepo.Verify(r => r.GetByIdAsync(projectId, default), Times.Once);
            mockProjectUserRepo.Verify(r => r.GetByProjectIdAsync(projectId, default), Times.Once);
        }

        #endregion
    }
}
