// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenUpMan.Data;

#nullable disable

namespace OpenUpMan.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OpenUpMan.Domain.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactType")
                        .HasColumnType("TEXT")
                        .HasColumnName("artifact_type");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("current_state");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("Mandatory")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mandatory");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phase_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("artifacts", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.ArtifactVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArtifactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("artifact_id");

                    b.Property<string>("BuildInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("build_info");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("FileBlob")
                        .HasColumnType("BLOB")
                        .HasColumnName("file_blob");

                    b.Property<string>("FileMime")
                        .HasColumnType("TEXT")
                        .HasColumnName("file_mime");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ArtifactId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("artifact_versions", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Iteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completion_percentage");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasColumnType("TEXT")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("phase_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("iterations", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Microincrement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ArtifactId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("artifact_id");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_url");

                    b.Property<int>("IterationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("iteration_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IterationId");

                    b.ToTable("microincrements", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ver detalles del proyecto",
                            Name = "proyecto:ver"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Actualizar información del proyecto",
                            Name = "proyecto:actualizar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Eliminar el proyecto",
                            Name = "proyecto:borrar"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Renombrar el proyecto",
                            Name = "proyecto:renombrar"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cambiar estado del proyecto",
                            Name = "proyecto:cambiar-estado"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Agregar usuarios al proyecto",
                            Name = "usuarios:agregar"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Eliminar usuarios del proyecto",
                            Name = "usuarios:eliminar"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Ver usuarios del proyecto",
                            Name = "usuarios:ver"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Modificar roles de usuarios",
                            Name = "usuarios:modificar-roles"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Ver fases del proyecto",
                            Name = "fases:ver"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Crear nuevas fases",
                            Name = "fases:crear"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Actualizar información de fases",
                            Name = "fases:actualizar"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Avanzar a la siguiente fase",
                            Name = "fases:avanzar"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Cambiar estado de fase",
                            Name = "fases:cambiar-estado"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Ver iteraciones",
                            Name = "iteraciones:ver"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Crear nuevas iteraciones",
                            Name = "iteraciones:crear"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Actualizar iteraciones",
                            Name = "iteraciones:actualizar"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Avanzar/completar iteraciones",
                            Name = "iteraciones:avanzar"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Eliminar iteraciones",
                            Name = "iteraciones:eliminar"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Ver microincrementos",
                            Name = "microincrementos:ver"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Crear microincrementos",
                            Name = "microincrementos:crear"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Actualizar microincrementos",
                            Name = "microincrementos:actualizar"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Eliminar microincrementos",
                            Name = "microincrementos:eliminar"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Agregar documentos a microincrementos",
                            Name = "microincrementos:agregar-documentos"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Ver artefactos",
                            Name = "artefactos:ver"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Crear artefactos",
                            Name = "artefactos:crear"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Actualizar artefactos",
                            Name = "artefactos:actualizar"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Eliminar artefactos",
                            Name = "artefactos:eliminar"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Subir versiones de artefactos",
                            Name = "artefactos:subir-version"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Descargar artefactos",
                            Name = "artefactos:descargar"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Marcar artefactos como obligatorios",
                            Name = "artefactos:marcar-obligatorios"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Cambiar estado de artefactos",
                            Name = "artefactos:cambiar-estado"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Acceso de solo lectura a todo",
                            Name = "solo-lectura"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Gestionar artefactos mínimos",
                            Name = "artefactos:minimos"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Ver reportes y métricas",
                            Name = "reportes:ver"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Generar reportes personalizados",
                            Name = "reportes:generar"
                        });
                });

            modelBuilder.Entity("OpenUpMan.Domain.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_index");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("phases", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.ProjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("project_users", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acceso completo al sistema, equivalente al Autor",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gestión del producto y artefactos",
                            Name = "Product Owner"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Facilitador del equipo y gestión de microiteraciones",
                            Name = "Scrum Master"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Desarrollo y entrega de artefactos",
                            Name = "Desarrollador"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pruebas y entrega de artefactos de testing",
                            Name = "Tester"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Solo lectura de todo el proyecto",
                            Name = "Revisor"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Creador del proyecto con todos los permisos",
                            Name = "Autor"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Visualización básica del proyecto",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("OpenUpMan.Domain.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 19,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 20,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 21,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 22,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 23,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 24,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 25,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 26,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 27,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 28,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 29,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 30,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 31,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 32,
                            PermissionId = 32,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 33,
                            PermissionId = 34,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 34,
                            PermissionId = 35,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 35,
                            PermissionId = 36,
                            RoleId = 7
                        },
                        new
                        {
                            Id = 36,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 37,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 38,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 39,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 40,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 41,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 42,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 43,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 44,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 45,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 46,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 47,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 48,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 49,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 50,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 51,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 52,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 53,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 54,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 55,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 56,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 57,
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 58,
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 59,
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 60,
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 61,
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 62,
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 63,
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 64,
                            PermissionId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 65,
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 66,
                            PermissionId = 31,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 67,
                            PermissionId = 32,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 68,
                            PermissionId = 34,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 69,
                            PermissionId = 35,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 70,
                            PermissionId = 36,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 71,
                            PermissionId = 33,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 72,
                            PermissionId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 73,
                            PermissionId = 8,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 74,
                            PermissionId = 10,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 75,
                            PermissionId = 15,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 76,
                            PermissionId = 20,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 77,
                            PermissionId = 25,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 78,
                            PermissionId = 30,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 79,
                            PermissionId = 35,
                            RoleId = 6
                        },
                        new
                        {
                            Id = 80,
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 81,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 82,
                            PermissionId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 83,
                            PermissionId = 5,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 85,
                            PermissionId = 10,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 86,
                            PermissionId = 11,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 87,
                            PermissionId = 12,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 88,
                            PermissionId = 13,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 89,
                            PermissionId = 14,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 90,
                            PermissionId = 15,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 91,
                            PermissionId = 16,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 92,
                            PermissionId = 17,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 93,
                            PermissionId = 18,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 94,
                            PermissionId = 20,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 95,
                            PermissionId = 21,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 96,
                            PermissionId = 22,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 97,
                            PermissionId = 24,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 98,
                            PermissionId = 25,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 99,
                            PermissionId = 26,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 100,
                            PermissionId = 27,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 101,
                            PermissionId = 29,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 102,
                            PermissionId = 30,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 103,
                            PermissionId = 31,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 104,
                            PermissionId = 32,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 105,
                            PermissionId = 34,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 106,
                            PermissionId = 35,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 107,
                            PermissionId = 36,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 108,
                            PermissionId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 109,
                            PermissionId = 8,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 110,
                            PermissionId = 10,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 111,
                            PermissionId = 15,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 112,
                            PermissionId = 17,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 113,
                            PermissionId = 20,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 114,
                            PermissionId = 21,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 115,
                            PermissionId = 22,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 116,
                            PermissionId = 24,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 117,
                            PermissionId = 25,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 118,
                            PermissionId = 26,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 119,
                            PermissionId = 27,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 120,
                            PermissionId = 29,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 121,
                            PermissionId = 30,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 122,
                            PermissionId = 34,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 123,
                            PermissionId = 35,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 124,
                            PermissionId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 125,
                            PermissionId = 8,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 126,
                            PermissionId = 10,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 127,
                            PermissionId = 15,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 128,
                            PermissionId = 20,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 129,
                            PermissionId = 24,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 130,
                            PermissionId = 25,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 131,
                            PermissionId = 29,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 132,
                            PermissionId = 30,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 133,
                            PermissionId = 35,
                            RoleId = 4
                        },
                        new
                        {
                            Id = 134,
                            PermissionId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 135,
                            PermissionId = 8,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 136,
                            PermissionId = 10,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 137,
                            PermissionId = 15,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 138,
                            PermissionId = 20,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 139,
                            PermissionId = 24,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 140,
                            PermissionId = 25,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 141,
                            PermissionId = 29,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 142,
                            PermissionId = 30,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 143,
                            PermissionId = 35,
                            RoleId = 5
                        },
                        new
                        {
                            Id = 144,
                            PermissionId = 1,
                            RoleId = 8
                        },
                        new
                        {
                            Id = 145,
                            PermissionId = 10,
                            RoleId = 8
                        },
                        new
                        {
                            Id = 146,
                            PermissionId = 15,
                            RoleId = 8
                        },
                        new
                        {
                            Id = 147,
                            PermissionId = 35,
                            RoleId = 8
                        });
                });

            modelBuilder.Entity("OpenUpMan.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Artifact", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Phase", null)
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenUpMan.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenUpMan.Domain.ArtifactVersion", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenUpMan.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenUpMan.Domain.Iteration", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Phase", null)
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenUpMan.Domain.Microincrement", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OpenUpMan.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OpenUpMan.Domain.Iteration", null)
                        .WithMany()
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenUpMan.Domain.Phase", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenUpMan.Domain.Project", b =>
                {
                    b.HasOne("OpenUpMan.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OpenUpMan.Domain.ProjectUser", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenUpMan.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenUpMan.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenUpMan.Domain.RolePermission", b =>
                {
                    b.HasOne("OpenUpMan.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenUpMan.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
